### ISSUE TITLE
Fatal error: Uncaught Error: Class ‘UPS\OAuthClientCredentials\Configuration’ not found in /

### ISSUE THREAD

**Issue by jav666** [abantecart/ups-php#19] opened 2024-05-27 16:52 UTC
after composer install:

_composer require abantecart/ups-php_

i successfully installed everything and adjusted the credentials in 

getAccessToken.php

and copy getAccessToken.php in root

unfortunately I only get:

_Fatal error: Uncaught Error: Class ‘UPS\OAuthClientCredentials\Configuration’ not found in /var/www/getAccessToken.php_

that's the simplest example, what's wrong with it?

**Comment by danielpost** [comment] 2024-05-28 09:38
Did you include the Composer autoloader at the top of your file? `require_once 'vendor/autoload.php';`

**Comment by jav666** [comment] 2024-05-28 10:56
![2024-05-28 12 54 31](https://github.com/abantecart/ups-php/assets/2657397/a24f56e8-8e6e-421d-ae6e-0e72ed576f3d)

yep.

**Comment by jav666** [comment] 2024-05-28 10:57
PHP version is  8.2.12

**Comment by danielpost** [comment] 2024-05-28 11:10
@jav666 I can reproduce on my end. I'll do some research and see if I can fix it.

**Comment by danielpost** [comment] 2024-05-28 13:08
@jav666 It seems like it can be fixed by adding this line:

`require_once __DIR__ . '/vendor/abantecart/ups-php/vendor/autoload.php';`

That being said, this seems like a bug that needs fixing—for some reason the classes do not get included in the normal autoloader. I suspect it has something to do with how [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) is implemented.

**Comment by jav666** [comment] 2024-05-28 13:13
but there is no "autoload.php" under this path '/vendor/abantecart/ups-php/vendor/autoload.php' ... and no "vendor" dir to

**Comment by jav666** [comment] 2024-05-28 13:13
just copy & paste?

**Comment by jav666** [comment] 2024-05-28 13:14
no, that doesn't work

**Comment by danielpost** [comment] 2024-05-28 13:15
Hmm, there is for me. I did run `composer update` inside the `ups-php` folder, so it's possible the file didn't exist before that. Give it a try and see if that works.

**Comment by jav666** [comment] 2024-05-28 13:17
yes. works. ok, thank you very much!

**Closed as completed** 2024-05-28 13:59 UTC

**Comment by danielpost** [comment] 2024-05-28 14:12
@abolabo If I may ask, what's the logic behind closing this as completed? It seems like there's some kind of bug in the autoloading logic, since you need to manually run `composer update` inside the package and include the nested autoloader file if you want to use this package.

The examples in their current form are broken.

**Comment by abolabo** [comment] 2024-05-28 14:21
@danielpost there is bug in the composer require command which does not work with wikimedia merge-plugin. As you noted correctly classes from directories are ignored by composer bin during build.  
If you download package from repo and run build with composer install command you will see your code will work fine. 
I don't know a solution for installation from packagist.org  (command composer require ...) 
Probably you can suggest?

**Comment by jav666** [comment] 2024-05-28 14:35
ok, I had a look under ‘closed’ ... apparently everyone had the problem, because it didn't work from start to finish

**Comment by krychu90** [comment] 2024-10-08 10:00
I have the same issue.
